### ISSUE TITLE
How to get a file with the suffix .tar.gz？

### ISSUE THREAD

**Issue by wertyhb-sns** [evanmy/keymorph#3]
How to get a file with the suffix .tar.gz？ the file in the data folder does not have a suffix.

**Comment by evanmy** [comment]
Hi, 

Refer to this section of the documentation

> The self-supervised pretraining, brain extractor and trained model weights are found in the ./data/ folder. Combine and decompress the files using:
> 
> cat ./data/weights* | tar xzpvf -
