### ISSUE TITLE
from functions.model import Simple_Unet, clean_mask error

### ISSUE THREAD

**Issue by wertyhb-sns** [evanmy/keymorph#4]
There is no Simple_Unet in functions.model, clean_mask these two classes, can you answer to help me?

**Comment by alanqrwang** [comment]
Hello, can you provide more information on your question and provide the full error stack?

**Comment by alanqrwang** [comment]
I see that it's called in the notebooks. Sorry about that, I missed that and deleted it! Just added those classes back in. Hope this resolves the issue.
